<a href="https://colab.research.google.com/github/Rwyszynski/Data-science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

s = pd.Series(data=[3, 2, 4, 6])
s

0    3
1    2
2    4
3    6
dtype: int64

In [ ]:
import pandas as pd
s = pd.Series(data=['python','java','sql'], name='languages')
s
df = pd.DataFrame(data=[12, 12, 32], index=['first', 'second', 'third'], columns=['col_1'])
df

col_1
first       12
second,     12
third       32

In [ ]:
df = pd.DataFrame(data={'WIG20': ['PKN ORLEN', 'PKO BP'], 'mWIG40': ['Amica', 'Playway']})
df

WIG20   mWIG40
0  PKN ORLEN    Amica
1     PKO BP  Playway

In [2]:
import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

sns.set()

sns.__version__

'0.13.1'

In [3]:
x = np.array([1,3])
x

array([1, 3])

In [5]:
x.dtype
x.shape

(2,)

In [6]:
y = np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

In [7]:
x = np.array(
    [[[4,2,1],
      [8,5,2]],
     [[2,8,5],
      [4,1,3]]

    ]

)
x

array([[[4, 2, 1],
        [8, 5, 2]],

       [[2, 8, 5],
        [4, 1, 3]]])

In [8]:
x.dtype='float'
x.dtype

dtype('float64')

In [10]:
x = np.zeros(shape=(4,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
x= np.full(shape=(3,3), fill_value=4, dtype ='int')
x

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [14]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x = np.arange(start=5, stop=10)
x

array([5, 6, 7, 8, 9])

In [18]:
x= np.linspace(start=10, stop=100, num=10)
x

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [25]:
x = np.arange(15)
x.reshape(3, 5)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
x = np.array([[1,3],[2,2]])
y = np.array([[2,8],[3,2]])

x*y

array([[ 2, 24],
       [ 6,  4]])

In [28]:
np.dot(x,y)

array([[11, 14],
       [10, 20]])

In [29]:
x.dot(y)

array([[11, 14],
       [10, 20]])

In [35]:
x=np.random.randn(10)
x

array([-0.25865251, -0.29425161, -0.70045987,  2.15152082, -0.15386129,
        0.26579018, -0.35450123, -0.9222886 , -0.713975  ,  0.37292919])

In [39]:
x = np.random.randint(10)
x

2

In [40]:
x = np.random.randint(low=10, high=101)
x

85

In [44]:
x=np.random.choice([4,2,5,4])
x

4

In [48]:
np.random.shuffle(x)
x

TypeError: object of type 'numpy.int64' has no len()

In [49]:
x = np.sqrt(9)
x

3.0

In [51]:
np.all([3,0,8])

False

In [52]:
A = [3,5,2]
np.argmax(A)

1

In [53]:
np.max(A)

5

In [55]:
Arr = np.array([[3,5],[2,1]])
Arr

array([[3, 5],
       [2, 1]])

In [58]:
Arr[:,-1]
Arr

array([[3, 5],
       [2, 1]])

In [62]:
Arr=Arr.T
Arr

array([[3, 2],
       [5, 1]])

In [64]:
b=np.eye(5, dtype='int')
b

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [66]:
A = np.array([[2,4],[1,-1]])
B = np.array([[10],[-1]])
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, B)
x

array([[1.],
       [2.]])